### ISSUE TITLE
Use Performance calculation from Subgraph

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#1]
## 📄 Context
Currently, for the APR calculation for the pools, we use a separate backend solution called [postgraphile](https://www.graphile.org/postgraphile/) due to some constraints in the TheGraph protocol we use as Backend. We will retire postgraphile, and the calculation will be served directly from our main backend (Subgraph).

## ✅ Solution
Start consuming the monthly and weekly performance from our main graphQL API for the `StakingPools`. Display it when the **apr** flag is disabled and **newPerformanceEnabled** is on.

* Add a new feature flag to have a controlled rollout of this change. (feature flag name `newPerformanceEnabled`).
* Add the new logic to fetch the new performance data. 
* Add the new logic to display the new columns based on the feature-flag being enabled/disabled
* The current extended components that deal with postgraphile API should stay in place(while transitioning) and continue to work when the `apr` flag is on.

## 📈 Subtasks

- [x] Create a new feature flag. (i.e. `newPerformanceEnabled`)
- [x] Add the logic to load and display the new performance when the feature flag is enabled and `apr` flag is disabled in the Performance pool table.
- [ ] Inside the pool info page, the Overview card `Pool Performance` for seven days should feed from the new calculation when `apr` is disabled and `newPerformanceEnabled` is **on**
- [x] Add tests.
- [x] Stories are updated.

## 🎯 Definition of Done (a.k.a DoD)

- [ ] When `apr` flag is disabled and `newPerformanceEnabled` is on, I can see the performance numbers coming from Subgraph.
- [ ] Tests are passing.
