### ISSUE TITLE
chore: Update primary graphQL endpoint setup

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#105]
## 📄 Context
Currently, we are leaving the endpoint versioned for the primary graphQL endpoint setup. Initially, that was alright, but if we need to replace it quickly, it would demand a new `code -> pr -> merge -> deployment`; the idea is to swap environment variables and re-deploy quickly if necessary. Also, in the case of repo `forks`, we are covered. 

## ✔️ Solution
Make it the primary graphQL URL for Goerli and Mainnet as configurable environment variables.

**PS: I will also use that issue to `refactor` some type of definition within the ISG code. It is always saying `never`**

## 📈 Subtasks

- [x] Change the primary GraphQL setup.
- [x] Fix ENS `ENSStaticProps`.

## 🎯 Definition of Done

- [x] CI passing
- [x] Vercel is building without problems
- [x] Deployment preview version is working as expected, already using the env vars.
