### ISSUE TITLE
Update staking pool creation

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#128]
## 📄 Context
Currently, we offer two commission models when creating a staking pool. that is, **Gas-based** and **Flat-rate** commissions. Based on the usage of both models, we will streamline and simplify to only offer the **Flat-rate** based. We currently have only one pool using Gas-based on mainnet that has no users and is "not active". 

## ✔️ Solution
Remove the Gas-based option in the `Commission Model` step in the node-runners staking pool creation feature.

## 📈 Subtasks

- [ ] Remove the Gas-based option.
- [ ] Validations are updated as required.
- [ ] Update tests related to that step.
- [ ] Update stories, if any.

## 🎯 Definition of Done

- [ ] **The staking pool creation flow is functioning as expected.**
- [ ] CI checks are passing.
- [ ] Vercel deployments have no problems.
