### ISSUE TITLE
Staking instructions alert not applying new colours (Private Node Management)

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#131]
## 📄 Context
The staking instructions warning alert icon does not apply any expected colours in dark or light mode (Gif below). That instruction card is located inside the **Private node management** area.

## Reference
![staking-instructions-private-node-management](https://github.com/cartesi/explorer/assets/1239768/726b1d89-5924-45f2-b8ae-42258fdfeb44)

## 📈 Subtasks

- [x] Apply the correct colours in Dark mode.
- [x] Apply the correct colours in Light mode.

## 🎯 Definition of Done

-   [x] Both dark and light mode matches the expected colour
