### ISSUE TITLE
Remove code related to the gas-based staking pools

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#143]
## 📄 Context
The creation of a gas-based pool was deprecated and removed from UI. The backend (i.e. GraphQL) was deployed without the types related to the gas-based Staking Pool. Therefore, doing a good clean-up in the front end is safe.

## ✔️ Solution
Remove and/or update **included but not limited to**  logic | components | graphql model definition | stories | tests. 

## 📈 Subtasks

- [ ] Check and apply changes to conditional logic related to gas-based staking pools.
- [ ] Check and apply changes to components related to the gas-based staking pools. 
- [ ] Check and apply changes to stories related to the gas-based staking pools.
- [ ] Check and apply changes to unit tests related to the gas-based staking pools.
- [ ] Check and apply changes to graphQL models related to the gas-based staking pools.
- [ ] **As mentioned in the Solution block, add any not explicitly listed areas affected.**

## 🎯 Definition of Done

- [ ] There are no leftovers related to the gas-based staking pools through the code.
- [ ] No side effects to the application
  - [ ] Staking pool creation flow is not affected.
  - [ ] Staking pool management is not affected.
  - [ ] Staking pool actions deposit|stake|unstake|withdraw is not affected.
- [ ] Github action CI continue to pass.
- [ ] Vercel deploy without problem.
