### ISSUE TITLE
Replace AWS subgraph with Chainstack's

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#15]
## 📄 Context
We will sunset subgraph support on our infrastructure, lowering costs and maintenance work. So we will be replacing the current AWS with another provider called [Chainstack](https://chainstack.com/)

## ✔️ Solution
Replace all AWS-related configurations with Chainstack's. That includes; 

* Update the GraphQL Apollo configurations.
* Update the ISR for the staking pool pages. 
* Check with the API stats needs any changes.
* Remove all the code related to the extended version.
* Remove any usage of the feature flags; `aws` and `apr` (all related to AWS and the extended version provided by Postgraphile )in the code base.

## 📈 Subtasks

- [ ] Create a feature flag to switch between hosted services and Chainstack. 
- [ ] Update graphQL Apollo configuration with Chainstack information
- [ ] Remove all code definitions related to the graphql extended version. i.e. components/hooks/tests/stories. 
- [ ] Check on API stats if any change is necessary. 
- [ ] Check on the [safe wallet](https://safe.global/careers) (a.k.a Gnosis Safe).

## 🎯 Definition of Done

- [ ] Running Staking in the Preview environment works seamlessly.
- [ ] Running Staking in a Production environment works seamlessly.
- [ ] Switch feature flag will change the data source without causing problems.

**Comment by brunomenezes** [comment]
That is a work in conjunction with [subgraph issue#13](https://github.com/cartesi/subgraph/issues/13)
