### ISSUE TITLE
Upgrade NextJS from 12 to 14

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#165]
## 📄 Context

NextJS is releasing version 15, which contains significant changes, including experimental moves towards `React Compiler` [more details here in the blog post](https://nextjs.org/blog/next-15). It would not be a problem for us to continue to run on version 12 if we were self-hosted, but as we use Vercel's infrastructure, it is a safe bet not to keep the version too far behind due to possible infrastructure changes that could affect us as we use a few features, e.g. **ISR.** 

## ✔️ Solution
As we already use the React@18, there should not be much regression problem with the react-library dependencies used here **(But keep that in mind).** 

* Node version minimum to be bumped to v18. Update the `engine` information in the package.json
* Continue to work inside [app.safe.global](https://app.safe.global)
* Keep the routing using the `/pages` rather than move to the `/app` router.
* Check the validations done in the forms.
* Check staking actions [allowance, deposit, stake, unstake, withdraw]. 
* Check the Pool management actions:
  * Create a pool 
    * hire a node 
    * manage the pool 
    * retire a pool node 
    * hire a new node 
    * deposit eth to the node
    * close staking in the pool
    * reopen the staking in the pool 
  * Create a private node.
    * manage the private node.
    * deposit eth to the private node.
    * retire the node.
* Check the `blocks` pages. 

## 📈 Subtasks

- [x] Upgrade NextJS to v14.
- [x] Check/update staking actions. 
- [x] Check/update node-runners workflows. 
- [x] Check/update blocks page. 
- [x] Check/update explorer opening inside the safe app.
- [x] Check/upgrade other react libraries (if necessary).
- [x] Check storybook.

## 🎯 Definition of Done

- [x] NextJS upgraded.
- [x] Staking actions are working. 
- [x] Pool and Private Node management are working. 
- [x] CI checks are passing.
- [x] Vercel build passing.
- [x] Deployed version can be opened inside [app.safe.global](https://app.safe.global)

**Comment by brunomenezes** [comment]
Closing as I am linking to closed PR #166
