### ISSUE TITLE
Optimize unit tests for apps/rollups

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/explorer#17]
## 📄 Context

We noticed that unit tests take a lot of time to execute while not containing anything heavy in terms of computations. 

Most of the time, those tests contain some mocks and simple checks that should be rather fast. Mocks are stored in memory and we are not calling any third-party services so the large amounts of time required for tests to execute are not justified. This also impacts our builds as they are slower than expected. 

## ✔️ Solution

There are multiple things we can do to improve unit tests speed. An example is to optimize imports since jest (our test runner) takes more time to process large imports than specific ones. 

Example from `packages/ui`:

This is slower:
```
import { StakePlusIcon } from '../../src/components';
```

than this:
```
import { StakePlusIcon } from '../../src/components/Icons';
```

## 📈 Subtasks

-   [ ] Optimize imports. Opt in for specific imports than global ones.
-   [ ] Investigate other ways to optimize tests using guides like https://jestjs.io/docs/29.0/troubleshooting and https://blog.bitsrc.io/why-is-my-jest-suite-so-slow-2a4859bb9ac0.
-   [ ] Investigate if we can run only new tests or tests for which the underlying components/modules have changed with https://jestjs.io/docs/cli#--onlychanged. This is for `test:ci` command.
-   [ ] Investigate if we can remove `--runInBand` flag for `test:ci`. For reference - https://jestjs.io/docs/cli#--runinband.

## 🎯 Definition of Done

-   [ ] Tests speed is increased so that we see significant improvement in build times.
