### ISSUE TITLE
Vercel Setup & Deployment

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#2]
## 📄 Context
As we move to the public repository, all the integrations must be set again. Also, as we are moving to a trunk-based development, the Vercel configuration for deployment will change, and production will be based on tag publishing only and the `main` and other branches for the preview environment.

## ✔️ Solution
Create new projects on Vercel for rollups and staking.  Keep the main branch as the default, but add a new branch to be the production representation and keep using the branch-based deploy on Vercel.

* Add projects
* `main` branch will be the preview environment (Preview Domain associated)
* `production` branch will be the one published on production environment. (Production domain associated)

## 📈 Subtasks

- [x] Create a new project on Vercel for Staking.
- [x] Create a new project on Vercel for Rollups.
- [x] Include the environment variables for each project.

## 🎯 Definition of Done

- [x] Production deployment is based only on the tag/production branch.
- [x] PR merges to `main` are deployed in preview mode and associated with the `https://preview.explorer.cartesi.io` domain.
