### ISSUE TITLE
Remove redundant package on apps/staking

### ISSUE THREAD

**Issue by dandheedge** [cartesi/explorer#22]
## 📄 Context

The current package in the explorer repository still exhibits redundancy in the wallet modules.

The package mentioned (apps/staking) has duplicate modules found in the packages/wallet directory:

package.json in apps/staking: [link](https://github.com/cartesi/explorer/blob/4b396f820b800935aa79543f9e22c4acd899929d/apps/staking/package.json#L30C8-L36C48)
package.json in packages/wallet: [link](https://github.com/cartesi/explorer/blob/4b396f820b800935aa79543f9e22c4acd899929d/packages/wallet/package.json#L34C10-L40C47)
The objective of this issue is to eliminate the redundancy, ensuring that the wallet packages are only loaded from the packages/wallet directory.

## 📈 Subtasks

-   [ ] Update the package.json on `apps/staking`
-   [ ] Make sure dependencies are updated in the lock file (yarn.lock).
- [ ] Bump package version on `packages/wallet`
-   [ ] Verify whether everything is working as expected.

Duplicate content, move to #24

**Comment by brunomenezes** [comment]
Hey @dandheedge, I just saw this one now. Probably a duplicate of yours, but have a look at the definition of done I added I think that is important to guarantee the work is really finished. 

#24

**Comment by dandheedge** [comment]
@brunomenezes okay, will close this issue and working on #24
