### ISSUE TITLE
Remove rollups v0.8.2 

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#23]
## 📄 Context
Rollups version v0.8.x helped the development team to build support for the local development of DApps. But since v0.9.0 is the target, we could remove everything related to v0.8.2.

## ✔️ Solution
Remove the dependency for rollups v0.8.2 and adapt the components that use it that support DApp local development.

- Remove @cartesi/rollups@0.8.2
- Change code logic that deals with 0.8.
- Run a v0.9.0 DApp locally and check that it works as expected. 

## 📈 Subtasks

- [x] Remove the @cartesi/rollups dependency for v0.8.2 
- [x] Code changes that remove the usage of v0.8.2 related code, e.g. factories for `InputFacet` and other hooks.
- [x] Run a DApp 0.9.0 locally and check the integration is working as expected, i.e. I can see my DApp details in the main screen.
- [x] Test changes (if required, given the above changes)

## 🎯 Definition of Done

- [x] Run on DApp local dev mode works as expected when using a DApp locally (i.e. hardhat local blockchain)
- [x] The web-deployed version that integrates with networks (Goerli, Arbitrum-Goerli) still works as expected.
- [x] CI checks are passing.
