### ISSUE TITLE
Update onboard dependencies and remove duplicates

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#24]
## 📄 Context
Onboard is the library used to deal with wallet integration. We need to upgrade the core library and all the extra modules. Also, eliminate the duplication of dependency between the package/wallet and apps/staking since we move to a monorepo setup.

```csv
Package                        Current Wanted Latest Workspace        Package Type URL
@web3-onboard/coinbase         2.2.0   2.2.0  2.2.4  staking          dependencies https://onboard.blocknative.com
@web3-onboard/coinbase         2.2.0   2.2.0  2.2.4  @explorer/wallet dependencies https://onboard.blocknative.com
@web3-onboard/core             2.11.0  2.11.0 2.20.2 staking          dependencies https://onboard.blocknative.com
@web3-onboard/core             2.11.0  2.11.0 2.20.2 @explorer/wallet dependencies https://onboard.blocknative.com
@web3-onboard/gnosis           2.1.5   2.1.5  2.1.10 staking          dependencies https://onboard.blocknative.com
@web3-onboard/gnosis           2.1.5   2.1.5  2.1.10 @explorer/wallet dependencies https://onboard.blocknative.com
@web3-onboard/injected-wallets 2.4.0   2.4.0  2.10.1 staking          dependencies https://onboard.blocknative.com
@web3-onboard/injected-wallets 2.4.0   2.4.0  2.10.1 @explorer/wallet dependencies https://onboard.blocknative.com
@web3-onboard/ledger           2.3.2   2.3.2  2.4.6  staking          dependencies https://onboard.blocknative.com
@web3-onboard/ledger           2.3.2   2.3.2  2.4.6  @explorer/wallet dependencies https://onboard.blocknative.com
@web3-onboard/react            2.4.1   2.4.1  2.8.7  staking          dependencies https://onboard.blocknative.com
@web3-onboard/react            2.4.1   2.4.1  2.8.7  @explorer/wallet dependencies https://onboard.blocknative.com
@web3-onboard/walletconnect    2.2.1   2.2.1  2.3.9  staking          dependencies https://onboard.blocknative.com
@web3-onboard/walletconnect    2.2.1   2.2.1  2.3.9  @explorer/wallet dependencies https://onboard.blocknative.com
```
## 📈 Subtasks

- [x] Remove the dependency from the staking App. 
- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Create the corresponding issue if an update requires major work.
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Verify whether the wallet is working as expected. i.e. User could submit the transitions
- [ ] Bump dependencies on the wallet package #28 

## 🎯 Definition of Done

- [x] Transaction can be done with success through the web application.
- [x] Transaction can be done with success through https://app.safe.global.
- [x] Transaction can be done with success using a hardware wallet (i.e. Ledger)
- [x] CI verifications are passing.
