### ISSUE TITLE
Bump dependencies for Wallet package

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#28]
## 📄 Context
Update the dependencies defined in the `packages/wallet`. 

**PS: That does not include the onboarding dependencies because it is worked on issue #24**

### Affected parts:
* apps/rollups
* apps/staking
* packages/services
* packages/ui

```text
Package                                Current  Wanted   Latest   Workspace            Package Type    URL
@unleash/proxy-client-react            3.3.0    3.3.0    3.6.0    @explorer/wallet     dependencies    https://github.com/Unleash/unleash-proxy-react#readme
@types/react-dom                       18.2.5   18.2.6   18.2.6   @explorer/wallet     devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom
@types/react                           18.0.26  18.2.14  18.2.14  @explorer/wallet     devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react
eslint                                 7.32.0   7.32.0   8.44.0   @explorer/wallet     devDependencies https://eslint.org
jest                                   29.3.1   29.5.0   29.5.0   @explorer/wallet     devDependencies https://jestjs.io/
jest-environment-jsdom                 29.3.1   29.5.0   29.5.0   @explorer/wallet     devDependencies https://github.com/facebook/jest#readme
jest-mock-extended                     2.0.9    2.0.9    3.0.4    @explorer/wallet     devDependencies https://github.com/marchaos/jest-mock-extended
typescript                             4.9.4    4.9.5    5.1.6    @explorer/wallet     devDependencies https://www.typescriptlang.org/
```

## 📈 Subtasks

- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Fix any problems introduced by the new lib version related to `Jest`. 
- [x] Fix any linter problems caused by the bump of the `eslint`.
- [x] Github CI is passing without problems. 
- [x] Vercel deployment is going through without problems.
- [ ] **Add here any extra task you consider necessary**. [Optional]
