### ISSUE TITLE
Bump dependencies for Utils package

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#29]
## 📄 Context
Update the dependencies defined in the `packages/utils`.

### Affected parts
* @explorer/wallet
* @explorer/ui

```text
Package                                Current  Wanted   Latest   Workspace            Package Type    URL
@types/react-dom                       18.2.5   18.2.6   18.2.6   @explorer/utils      devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom
@types/react                           18.0.26  18.2.14  18.2.14  @explorer/utils      devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react
eslint                                 7.32.0   7.32.0   8.44.0   @explorer/utils      devDependencies https://eslint.org
typescript                             4.9.4    4.9.5    5.1.6    @explorer/utils      devDependencies https://www.typescriptlang.org/
```

## 📈 Subtasks

- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Verify whether all the parts are working as expected.
- [x] GitHub CI is passing.
- [x] Vercel deployment is going through without problems.
