### ISSUE TITLE
Bump dependencies on explorer root-project

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#30]
## 📄 Context
Update dependencies defined in the root project to avoid staying behind. Just be mindful of the ones with `major` bumps. 

```text
Package                                Current  Wanted   Latest   Workspace            Package Type    URL
@chakra-ui/icons                       2.0.10   2.0.10   2.0.19   explorer             dependencies    https://github.com/chakra-ui/chakra-ui#readme
@chakra-ui/react                       2.3.4    2.3.4    2.7.1    explorer             dependencies    https://chakra-ui.com/
@chakra-ui/theme-tools                 2.0.11   2.0.11   2.0.18   explorer             dependencies    https://github.com/chakra-ui/chakra-ui#readme
@unleash/proxy-client-react            3.3.0    3.3.0    3.6.0    explorer             dependencies    https://github.com/Unleash/unleash-proxy-react#readme
unleash-proxy-client                   2.2.1    2.2.1    2.5.0    explorer             dependencies    https://github.com/unleash/unleash-proxy-client-js#readme
turbo                                  1.6.3    1.10.7   1.10.7   explorer             devDependencies https://turbo.build/repo
prettier                               2.8.2    2.8.8    2.8.8    explorer             devDependencies https://prettier.io
framer-motion                          4.1.17   4.1.17   10.12.18 explorer             dependencies    https://github.com/framer/motion#readme
```

## 📈 Subtasks

- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Fix any API-breaking changes or deprecations in the new lib version for `Chakra-UI`.
- [x] Fix any API-breaking changes or deprecations in the new lib version for `Unleash`.
- [x] Fix any API-breaking changes or deprecations in the new lib version for `framer-motion`.
- [x] Fix any code formatting issues caused by the `prettier` version. If any
- [x] Verify whether the GitHub CI is passing.
- [x] Verify Vercel deployments are going through without problems.
