### ISSUE TITLE
Bump dependencies for UI package

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#31]
## 📄 Context
Update the dependencies defined in the `packages/ui` to avoid staying behind too much. 

### Affected parts 
* apps/rollups
* apps/staking

> **Note**: Be mindful of major bumps

```text
Package                                Current  Wanted   Latest   Workspace            Package Type    URL
eth-chains                             1.0.0    1.0.0    2.0.0    @explorer/ui         dependencies
ethers                                 5.4.7    5.4.7    6.6.2    @explorer/ui         dependencies    https://ethers.org
humanize-duration                      3.27.0   3.27.0   3.28.0   @explorer/ui         dependencies    https://github.com/EvanHahn/HumanizeDuration.js
react-icons                            4.9.0    4.9.0    4.10.1   @explorer/ui         dependencies    https://github.com/react-icons/react-icons#readme
@storybook/addon-actions               6.5.15   6.5.16   7.0.24   @explorer/ui         devDependencies https://github.com/storybookjs/storybook/tree/next/code/addons/actions
@storybook/addon-essentials            6.5.15   6.5.16   7.0.24   @explorer/ui         devDependencies https://github.com/storybookjs/storybook/tree/next/code/addons/essentials
@storybook/addon-links                 6.5.15   6.5.16   7.0.24   @explorer/ui         devDependencies https://github.com/storybookjs/storybook/tree/next/code/addons/links
@storybook/react                       6.5.15   6.5.16   7.0.24   @explorer/ui         devDependencies https://github.com/storybookjs/storybook/tree/next/code/renderers/react
@testing-library/react                 13.4.0   13.4.0   14.0.0   @explorer/ui         devDependencies https://github.com/testing-library/react-testing-library#readme
@types/humanize-duration               3.25.1   3.25.1   3.27.1   @explorer/ui         devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/humanize-duration
@types/react                           18.0.26  18.2.14  18.2.14  @explorer/ui         devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react
@types/react-dom                       18.2.5   18.2.6   18.2.6   @explorer/ui         devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom
eslint                                 7.32.0   7.32.0   8.44.0   @explorer/ui         devDependencies https://eslint.org
jest                                   29.3.1   29.5.0   29.5.0   @explorer/ui         devDependencies https://jestjs.io/
jest-canvas-mock                       2.5.1    2.5.2    2.5.2    @explorer/ui         devDependencies https://github.com/hustcc/jest-canvas-mock#readme
jest-environment-jsdom                 29.3.1   29.5.0   29.5.0   @explorer/ui         devDependencies https://github.com/facebook/jest#readme
jest-mock-extended                     2.0.9    2.0.9    3.0.4    @explorer/ui         devDependencies https://github.com/marchaos/jest-mock-extended
storybook-addon-apollo-client          4.1.4    4.1.4    5.0.0    @explorer/ui         devDependencies https://github.com/lifeiscontent/storybook-addon-apollo-client#readme
storybook-addon-next-router            3.1.1    3.1.1    4.0.2    @explorer/ui         devDependencies https://github.com/lifeiscontent/storybook-addon-next-router#readme
storybook-addon-performance            0.16.1   0.16.1   0.17.1   @explorer/ui         devDependencies https://github.com/atlassian-labs/storybook-addon-performance#readme
typescript                             4.9.4    4.9.5    5.1.6    @explorer/ui         devDependencies https://www.typescriptlang.org/
```

## 📈 Subtasks

- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Verify whether all the parts are working as expected.
- [x] GitHub CI is passing.
- [x] Vercel deployment is going through without problems.
- [x] #33
- [x] #37
- [x] #41

**Comment by brunomenezes** [comment]
Folks (@nevendyulgerov , @dandheedge ), 
I've been breaking the `outdated` reports into smaller issues by context, but even these "bits" compress too much. 
Today in our meeting, I want to discuss an approach I work in the past and exchange ideas for this kind of issue that is a bit bigger in the sense of possible breaking changes—this one, for instance, touches multiple parts like `storybook`, `jest`, `typescript`, `ethers` etc. I am not just talking about making that an `epic` combined with [tracked tasklists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists) but an approach on feature-branches and PRs, I am thinking for the sake of who is reviewing because it ended-up a huge PR with multiple complex changes and becomes a tedious work cognitively hard to grasp ending up on `LGTM` 😏.
