### ISSUE TITLE
Move rollups docker packaging from QEMU

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#35]
## 📄 Context
We have been using [QEMU](https://github.com/docker/setup-qemu-action) to generate our rollups docker image. Previously it was only generating the images using the **Linux/amd64** architecture, and the times were reasonable, around 6 minutes without intermittent connectivity problems. Once we included the **Linux/arm64**, though, the timing for that generation alone is around 26 minutes, and we often see network connectivity problems (screenshot below) naturally followed by CI failure because it usually never recovers that connection. Therefore, we are looking for an alternative to solve that problem and avoid the **workaround**, that is, to rerun it 🫠.

<img width="689" alt="Screenshot 2023-07-06 at 12 12 55" src="https://github.com/cartesi/explorer/assets/1239768/0ee7aa8c-d7d2-4fb0-9c63-2b77dd606d0d">

## ✔️ Solution
Initially, move from QEMU to [depot.dev](https://depot.dev), which is specialised in building docker images. **PS: funny enough, the example on the main page is showing how fast it is to build something on arm64**

Reference: [Sunodo CLI Action](https://github.com/sunodo/sunodo/blob/main/.github/workflows/sdk.yaml) 

## 📈 Subtasks

- [x] Create a `DEPOT_PROJECT` for rollups-explorer on depot.dev. 
- [x] Add the `DEPOT_PROJECT` in the repository vars config to be available to the GitHub action.
- [x] Update permissions in the [docker-rollups.yml](https://github.com/cartesi/explorer/blob/main/.github/workflows/docker-rollups.yml) including `id-token: write` to be able to request `JWT` token.
- [x] Add setup steps to integrate with `depot.dev`

## 🎯 Definition of Done

- [x] The intermittent CI connectivity failure is solved
- [x] `rollups-explorer` images are published to the [GitHub Registry](https://github.com/cartesi/explorer/pkgs/container/rollups-explorer) a.k.a packages.

**Comment by brunomenezes** [comment]
@tuler, 
I saw Sunodo's CLI CI code, and I have a question; 

1. Do we have a common account on depot.dev? If yes, please give me access or create a project on depot for us.
