### ISSUE TITLE
Upgrade rollups to the latest version

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#46]
## 📄 Context
Currently, we are using the @cartesi/rollups@0.9.0, but a new version (0.9.1) was released last month. Let's bump the performance to keep following the latest updates.

## 📈 Subtasks

- [ ] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [ ] Make sure dependencies are updated in the lock file (yarn.lock).
- [ ] Verify whether previously listed DApps on Goerli and/or Arbitrum Goerli are still listed.
- [ ] Create the corresponding issue if an update requires significant work.

**Comment by brunomenezes** [comment]
We are closing this PR. Since we are removing Rollups app from this repository (PR #140 )
