### ISSUE TITLE
Option to auto check for new inputs

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#47]
## 📄 Context
In the rollups explorer, we list the latest N inputs that could contain **notices, reports, and vouchers** in the DApp details view. But a hard refresh would be needed to check for new Inputs that may have come through. Not bad, but a better experience could be added to fetch the latest data. 

## ✔️ Solution
A switch should be added in the DApp details view to start the fetching process of the latest inputs. A few key points below;

* Add a switch UI to start the whole process. Component reference [here](https://chakra-ui.com/docs/components/switch)
* Add a pooling/interrogation mechanism to check for the latest data.
* If a list of items already exists, it should not disrupt the current state of it, meaning to avoid complete list replacement but rather append to it.
* **Upgrades to the GraphQL Mock server are required to support further development.**

## 📈 Subtasks

- [ ] Augment the **graphQL mock server** capabilities to add new inputs promptly after it starts.
- [ ] Include the switch to the left side of the search input.
   - [ ] The copy is `Enable auto refresh?` followed by the switch. 
   - [ ] The switch should be off by default.
   - [ ] Once the user changes the switch, It should persist through all the DApp and page refreshes. So persist the configuration, e.g. Local-storage.
- [ ] Implement polling/interrogation mechanism
   - [ ] Add/change query definition for inputs to support this filtering. e.g. `inputEdge`
   - [ ] If an initial list of inputs exists, it should be appended rather than full creation. _(That usually avoids massive flickering)_
- [ ] Include tests to cover new code added.
- [ ] **Add any extra task in case of oversight.** [Optional]

## 🎯 Definition of Done

- [ ] When the switch is **on**, the inputs come into the list automatically without the need to refresh the page.
- [ ] The request should stop when the switch is changed back to its off position.
- [ ] CI is passing without problems.
- [ ] Vercel deployment is going through without problems.

**Comment by brunomenezes** [comment]
@tuler, 
We don't have a subscription in the DApp graphQL, right? 

I tried to mention Ligneul here but he is not showing up 🤷‍♂️.

**Comment by nevendyulgerov** [comment]
Hi @brunomenezes , I think we can close this one as we recently removed the `rollups` app from the monorepo.
