### ISSUE TITLE
Remove GraphQL schema for v0.8

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#48]
## 📄 Context
We made some house cleaning for old versions of rollups (i.e., rollups v0.8.2), but some definitions are still lingering around and another round of cleaning is necessary.

## ✔️ Solution
Remove and delete the graphQL schema definition for v0.8. 

## 📈 Subtasks

- [ ] Remove definitions and folder for the `schema.graphql` for v0.8. located on `graphql/schema/v0.8.`
- [ ] Check for any reference in the **codegen.yml** that must be removed. 
- [ ] Check for any tests that may have reference to it.

## 🎯 Definition of Done

- [ ] CI checks, and tests are passing.
- [ ] Codegen is working as expected.
- [ ] Vercel deployment is going through without problems.

**Comment by nevendyulgerov** [comment]
It appears that this is already done. Closing.
