### ISSUE TITLE
Add message when DApp has no inputs 

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#49]
## 📄 Context
The DApps details view currently shows a message for error when there are problems with the guessed URL, or it lists the inputs in case we have data. For the use case where the graphQL connection is established without problems, but there are no Inputs, we display an empty body below the search. It is not bad; however, we can do a bit a better 👍 

## ✔️ Solution
Display a centralised message to provide feedback that all is well, but the DApp has not produced any inputs yet. The key points are;

* Only display such a message when; no errors happen on the graphQL side, and there are no data back from the fetch.
* Otherwise, it should not be displayed.

## 📈 Subtasks

- [ ] Centralise an informative notification below the search area with the following copy `Looks like there are no inputs yet...`
- [ ] Add new test cases to cover the new code.
- [ ] **Add any extra task in case of oversight ** [optional]

## 🎯 Definition of Done

- [ ] Should display the above copy when the connection is established, but there are no data to display.
- [ ] CI checks and new test cases are passing.
- [ ] Vercel deployment is going through without problems.
