### ISSUE TITLE
Add the new colours to the theme (e.g. Cyan, Teal, Support system colours, etc.)

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#55]
## Context 
The new brand requires a new set of colours to support the overall looking and feel of the applications, i.e. Staking and Rollups.

**PS: Refer to the parent issue for design references.** 

## Solution 
Include the new set of colours to support the system. **As a suggestion, the reference colours are single instead of pallets, so I suggest being mindful and using the same language used by the design team, for example;**

[Suggestion]: Adding to the theme's colours definition;
```javascript
{
 dark: {
   support: {
     success: #BDE08D,
     alert: #FEB274,
     error: #FF8D78
   }
 }
}
```

> Later, we could refine and leverage the use of Chakra-ui [Sematic Tokens](https://chakra-ui.com/docs/styled-system/semantic-tokens)
## Subtasks

- [x] Add the new base dark mode colours (Dark mode)
- [x] Add the new Digital product UI colours definition (Dark mode)
- [x] Add the new support system colours (Dark mode)

## Definition of done

- [x] The new values are included in the theme's colour configuration.
