### ISSUE TITLE
Update the home page colours and skin tones.

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#56]
## 📄 Context
Here are the home page changes on colour, skin tones and fonts in Dark mode to comply with the new Cartesi brand. The application's structure did not change, only the look and feel.

**PS: Refer to the parent of this issue for references on colours, fonts and the overall look and feel of a page.**
PS²: Don't worry about the **header** and **footer**, because that is addressed in a separate issue #62 

## 📈 Subtasks
> A Home page example is already in the Figma file for Dark mode for easier reference. 

### Overall
- [x] Make sure the fonts are applied correctly based on the Figma description. i.e.  Where to use each font and what size and weight to be applied.
- [x] Make sure the components are round, like the design. **We're transitioning from a squared-based design to a round one.**
### Page sessions
- [x] Check if the new colours for the page name, wallet balance, and pool balances are correct. Apply changes if needed. 
- [x] Apply colour changes to the `Block` space. **Keep the current grid system of 2 columns for big screens and 1 column for small ones for the Card.** 
- [x] Apply colour changes to the `Block Producers` space. 
    - [x] Update the look and feel of the Table.
    - [x] Update the Address component, **replace the light blue background with an underline in the address text.**. 
    - [x] Update the `staking` button colour in the `stake/info` column.
    - [x] Update the paging component to match design specs. 
- [ ] **Add here any extra tasks you see fit [Optional]**

## 🎯 Definition of Done

-   [x] Home page matches the design specs on Figma.
