### ISSUE TITLE
Update the node-runners page colours and skin tones.

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#59]
## 📄 Context
Here are the `node runners` main page changes on colour, skin tones and fonts in Dark mode to comply with the new Cartesi brand. The application's structure did not change, only the look and feel.

**PS: Refer to the parent of this issue for references.**
PS²: Don't worry about the **header** and **footer**, because that is addressed in a separate issue #62 

## 📈 Subtasks

**PS: A highlight for the two `cases` below. observe the spacing and difference in colours in between blocks, meaning they are not glued.**

### Overall
- [x] Make sure the fonts are applied correctly based on the Figma description. i.e.  Where to use each font and what size and weight to be applied.
- [x] Make sure the components are round, like the design. **We're transitioning from a squared-based design to a round one.**
### Page sessions
- [x] For the page header area:
  - [x] apply new colour and font rules for page **title** and **subtitle**. 
  - [x] **when wallet is disconnected**: Apply the new colour and font rules in the alert and connect area.
  
### Case: when the user doesn't have either Staking Pool or Private node
- [x] Apply colours and font rules to the `Create a node or pool in steps` title.
- [x] Apply colours and font rules for the `Create a public pool` card.
  - [x] Update the icon colour
  - [x] Update the button colour 
  - [x] Apply the new colours for the tooltip content (e.g. background colour, font). 
- [x] Apply colours and font rules for the `Run a private node` card.
  - [x] Update the icon colour
  - [x] Update the button colour 
  - [x] Apply the new colours for the tooltip content (e.g. background colour, font). 
- [ ] **Add here any extra tasks you see fit [Optional]**

### Case: when there is a Staking Pool and/or Private Node created

- [x] For the `Pool` block
   - [x] Apply the new font rules to the title.
   - [x] Apply colours changes to the `create pool` button
   - [x] Update the look and feel of the **Table** (check on Figma for table colours reference)
- [x] For the `Private node` block
   - [x] Apply the new font rules to the title.
   - [x] Update the look and feel of the **Table** (check on Figma for table colours reference)

## 🎯 Definition of Done

-   [ ] Node runners' main page matches the design specs on Figma.
