### ISSUE TITLE
Update: Rollups Docker image generation.

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#6]
## 📄 Context
Currently, when a tag it will also start an action to package a docker image for rollups to be published not just on the GitHub container registry but also on the docker hub. But we need the credentials set in the repository to publish the image. **Also, change how we trigger the GA for rollups-explorer docker image generation.**

_PS: Added extra things in bold_

## ✔️ Solution
Add the docker hub credentials to the repository settings to be available for our GitHub actions. Also, we will trigger the GitHub action for rollups packaging based on tag versioning.

* Include secrets for docker-hub in the repo settings
* Update the GitHub action to be triggered when matching a rollups-related tag version. i.e. `rollups@0.9.0`, which results in a docker image tag like cartes/rollups-explorer:0.9.0
* Update documentation to clarify how the image publishing works.

## 📈 Subtasks

- [x] Add the secrets to connect to the docker hub and publish the image.
- [x] Update the GitHub that package rollups-explorer image based on tag as abovementioned. 
- [x] Update documentation about the rollups-explorer image publishing.

## 🎯 Definition of Done

- [x] The docker image for `explorer-rollups` could be published to the docker hub.
- [x] The GitHub action is updated with the abovementioned tag matching.
- [x] Documentation is with the rollups docker image publishing process.

**Comment by tuler** [comment]
Just use the secrets.
DOCKER_USERNAME
DOCKER_PASSWORD

**Comment by brunomenezes** [comment]
> Just use the secrets. DOCKER_USERNAME DOCKER_PASSWORD

These are the secrets we are calling in the GA. [here](https://github.com/cartesi/explorer/blob/main/.github/workflows/docker-rollups.yml#L65)

But the action failed anyway. [Action log here](https://github.com/cartesi/explorer/actions/runs/5172989075/jobs/9317841049)

**Comment by brunomenezes** [comment]
I updated the title + content.
