### ISSUE TITLE
Update header and footer colours, and skin tones.

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#62]
## 📄 Context
That is a one-off change in the navbar and footer that will benefit the work to be done on multiple pages.

**PS: Refer to the parent of this issue for references.*

## 📈 Subtasks

- [x] Make sure the fonts are applied correctly based on the Figma description. i.e.  Where to use each font and what size and weight to be applied.
- [x] Apply colour changes to the `NavBar` space where the Logo, links and wallet button lies. 
- [x] Apply colour changes to the `Footer` space. 

## 🎯 Definition of Done

-   [x] The NavBar and Footer match the design specs.
