### ISSUE TITLE
yarn storybook command not working properly

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#75]
## 📄 Context
Currently, we are using Storybook, and for every pull-request and push, we publish to Chromatic. Apparently, it works as expected since we use the storybook-build command and publish the folder with the static content. But if we use the `yarn storybook` command inside the **apps/staking** folder, for example, or in the root of the project through `turborepo task,` the build goes well (without any failures), the app opens, but all the stories display this `Storybook preview hook` error message.

## ✔️ Solution
Recently we did some upgrades in the storybook libs/deps. An investigation would be necessary to see in which tag for example that problem may have been introduced, the tags may help to narrow down the changes since we have compares defined inside the CHANGELOG.md. 

## 📈 Subtasks

- [x] Investigate where the `yarn storybook` command stops working properly.
- [x] Apply the changes to fix the configuration/code that is causing the trouble.

## 🎯 Definition of Done

-   [x] Running `yarn storybook` renders the stories without problem.
