### ISSUE TITLE
Add new colours to the theme (Light Mode)

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#81]
## Context 
The new brand requires a new set of colours to support the overall looking and feel of the applications, i.e. Staking and Rollups.

**PS: Refer to the parent issue for design references.** 

## Solution 
Include the new set of colours to support the system. **As a suggestion, the reference colours are single instead of pallets, so I suggest being mindful and using the same language used by the design team, for example;**

[Suggestion]: Adding to the theme's colours definition;
```javascript
{
 light: {
   support: {
     success: #7CA154
     alert: #FFA77A,
     error: #FD7267,
     info: #B5E8F4
   }
 }
}
```

> Later, we could refine and leverage the use of Chakra-ui [Sematic Tokens](https://chakra-ui.com/docs/styled-system/semantic-tokens)
## Subtasks

- [x] Add the new base light mode colours (Light mode).
- [x] Add the new Digital product UI colour definition, i.e. the shades of grey (Light mode).
- [x] Add the new support system colours (Light mode).

## Definition of done

- [x] The new values are included in the theme's colour configuration.
