### ISSUE TITLE
Update the Onboard wallet modal (Light mode)

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/explorer#97]
## Context 
The new brand has new colours and font to be applied. So we could also extend the new look and feel to third-party components we use

**PS: Refer to the parent issue for Figma design reference.** 

## Solution 
To the possible extent, update the web3-onboard theme colours with the new colours and font rules. We already have some customisation using the exposed CSS variables, so that would be an update to the current one. `ui/src/styles/onboard.ts`

Onboard custom style docs: [https://onboard.blocknative.com/docs/getting-started/custom-styling](https://onboard.blocknative.com/docs/getting-started/custom-styling)

## Subtasks

- [x] Update existing onboard custom theme definition (Light mode)

## Definition of done

- [x] The onboard modal has the new Light mode look and feel based on the available colours from Figma designs.
- [x] The onboard modal look and feel match on Staking. 
- [x] The onboard modal look and feel match on Rollups.

**Comment by brunomenezes** [comment]
**PS: Evaluate what the light mode currently is when using web3-onboard. It may be good enough to blend in with the current light mode, and nothing needs to be done here.**
